#!/bin/bash

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1
if [[ -z "$source" ]]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi
# for jq
PATH=/usr/local/bin:$PATH
export TMPDIR=${TMPDIR:-/tmp/hello}
mkdir -p "${TMPDIR}"
payload=$(mktemp "$TMPDIR/resource-request.XXXXXX")
cat > "$payload" <&0

org=$(jq -r '.params.org // ""' < "$payload")
space=$(jq -r '.params.space // ""' < "$payload")


echo "setting target"  >&2

cf target -o $org -s $space
echo "checking cf apps"  >&2
echo cf apps >&2